### ISSUE TITLE
Is gon2n 0.0.3 not compatible with n2n 2.8.0?

### ISSUE THREAD

**Issue by Droid-MAX** [pojntfx/gon2n#6]

**Comment by pojntfx** [comment]
I’d have to check that; it is possible that n2n have changed their internal protocol in between the last compile time and now. If so, compiling a new version should fix the issue; currently, I don’t run the CI/CD workflow when the upstream repo changes.

**Comment by pojntfx** [comment]
I've updated the n2n sources to 2.8.0; it should be compatible now.
