### ISSUE TITLE
What is the management port used for?

### ISSUE THREAD

**Issue by Droid-MAX** [pojntfx/gon2n#7]

**Comment by pojntfx** [comment]
It's n2n internal; seems to be for managing the supernode.

**Comment by Logan007** [comment]
The management port offers some information on current edge or supernode status respectively. The [FAQ](https://github.com/ntop/n2n/blob/dev/doc/Faq.md) contains two short sections about it.

You can query by `netcat -u localhost <port number>` and then pressing ENTER (again).
