### ISSUE TITLE
I use xgo to compile an error

### ISSUE THREAD

**Issue by ld-2021** [pojntfx/gon2n#8]
![image](https://user-images.githubusercontent.com/78072815/106588433-bc59f580-6585-11eb-9c92-9ee3335bc32b.png)

**Comment by pojntfx** [comment]
Hi! I haven't tested xgo for cross-compilation, but I've just pushed some changes which set up cross-compilation for the clients.

**Comment by ld-2021** [comment]
How to compile?
Can I have a tutorial

**Comment by ld-2021** [comment]
I use make error
![image](https://user-images.githubusercontent.com/78072815/106746388-707a7f80-665d-11eb-8c9e-af6bf272d6a1.png)

**Comment by ld-2021** [comment]
system info  Ubuntu 20.04.1 LTS
Linux version 5.4.0-58-generic (buildd@lcy01-amd64-004) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020

**Comment by ld-2021** [comment]
@pojntfx

**Comment by pojntfx** [comment]
Hmmm, that's weird; CI runs on 18.04, it works there. Have you tried setting up the environment (protoc etc.) as described in the workflow (https://github.com/pojntfx/gon2n/blob/master/.github/workflows/make.yaml)?

**Comment by pojntfx** [comment]
It should build with the following:

```shell
go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
make clean
make -j$(nproc)
```

Binaries should be found in the `out` directory.

**Comment by ld-2021** [comment]
It's the same mistake



make: *** [Makefile:18: generate] Error 1

**Comment by ld-2021** [comment]
I'll try another system. If there are still problems, I'll contact you again

**Comment by pojntfx** [comment]
I've also created a release: https://github.com/pojntfx/gon2n/releases/tag/v0.1.0 it includes the binaries built by the CI system so you don't have to build it yourself ;)

**Comment by ld-2021** [comment]
This error occurred

Makefile:18: recipe for target 'generate' failed
![image](https://user-images.githubusercontent.com/78072815/106758817-ee925280-666c-11eb-82f8-151a513d3bb8.png)

**Comment by ld-2021** [comment]
I hope I can compile by myself, so that I can modify this program. Thank you

@pojntfx

**Comment by pojntfx** [comment]
Oh, sure ^^ Would you mind sharing the full build log from the start? The error should be above what you've posted, I'm assuming something like protoc is missing (the `generate` target builds n2n as a library and compiles the protobufs) ...

**Comment by ld-2021** [comment]
Thank you very much. I can pack it normally. I have another question. Now it's all 64 bit, but there are no 32-bit. Is there any other platform that can produce a full platform package, including the mobile terminal?

**Comment by pojntfx** [comment]
That should be possible, but due to n2n being written in C and the bindings being implemented in CGo, cross-compilation is somewhat harder then normally (I do currently only cross-compile the clients, as they don't depend on CGo). I'll look into cross-compilation. What is your exact target platform? `arm64`, `armv8`?

**Comment by ld-2021** [comment]
Thanks for your help, i need  android and ios

**Comment by pojntfx** [comment]
Android should be doable (only with root though I think), iOS is to restrictive to allow for Layer 2 TAP devices. Take a look at #5 for some more docs on how to run on Android, @Droid-MAX seems to have gotten it to work. I'm setting up an ARM64 cross-compilation setup atm.

**Comment by ld-2021** [comment]
Thanks, I closed the question
