### ISSUE TITLE
about the features of gon2n? 

### ISSUE THREAD

**Issue by TomLiu-GitHub** [pojntfx/gon2n#9]
Sorry, I don't fully understand the role of gon2n. Is it used to manage all the Supernodes and edges nodes of n2N?
Does it contain n2n? Just managing n2n also includes the function of n2n? Do I need to install n2n extra?
Is it just management?

**Comment by pojntfx** [comment]
Hi! gon2n includes n2n (I've written CGo bindings), no external installation is necessary.

**Comment by pojntfx** [comment]
Feel free to re-open if you have further questions.

**Comment by Droid-MAX** [comment]
The gon2n of different platforms is not suitable, including Edge and Supernode must be static cross-compilation, this is very confusing.

**Comment by Droid-MAX** [comment]
There are still two components related to cross-compilation-related issues, especially two components of edged and supernoded.
